#
# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2016-2022, Intel Corporation
#

#
# Dockerfile - a 'recipe' for Docker to build an image of ubuntu-based
#              environment prepared for running tests of pmdk-convert.
#

# Pull base image
FROM ubuntu:22.04
MAINTAINER piotr.balcer@intel.com

ENV DEBIAN_FRONTEND noninteractive

# Additional parameters to build docker without building components
ARG SKIP_SCRIPTS_DOWNLOAD

# Update the Apt cache and install basic tools
RUN apt-get update && apt-get dist-upgrade -y

# base deps
ENV BASE_DEPS "\
	autoconf \
	clang \
	cmake \
	curl \
	debhelper \
	devscripts \
	gcc \
	gdb \
	git \
	libunwind8-dev \
	libtext-diff-perl \
	pkg-config \
	sudo \
	tzdata \
	wget \
	whois \
	libndctl-dev \
	libdaxctl-dev"

# Install all required packages
RUN apt-get install -y --no-install-recommends \
	$BASE_DEPS \
&& rm -rf /var/lib/apt/lists/*

# Add user
ENV USER user
ENV USERPASS p1a2s3s4
RUN useradd -m $USER -g sudo -p `mkpasswd $USERPASS`
USER $USER

# Set required environment variables
ENV OS ubuntu
ENV OS_VER 22.04
ENV PACKAGE_MANAGER deb
ENV NOTTY 1
